services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: q#w2MS8#uiF5HDt  # Make sure this password is defined
      MYSQL_DATABASE: CatalogDB

    ports:
      - "3306:3306"
    networks:
      - network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - network

  Catalog:
    build: ./Catalog
    container_name: catalog-server
    image: catalog
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./Catalog/.env  # Load environment variables from the .env file
    networks:
      - network
    ports:
      - "302:302"

  Customer:
    build: ./Customer
    container_name: customer-server
    image: customer
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./Customer/.env  # Load environment variables
    networks:
      - network
    ports:
      - "301:301"

  Order:
    build: ./Order
    container_name: order-server
    image: order
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./Order/.env  # Load environment variables
    networks:
      - network
    ports:
      - "300:300"

networks:
  network:
    driver: bridge

