services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_PASSWORD: q#w2MS8#uiF5HDt
      MYSQL_DATABASE: catalogDB
    ports:
      - "3306:3306"
    networks:
      - network
    healthcheck:
      test: ["CMD", "mysqlcatalog", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - network

  Catalog:
    build: ./catalog
    container_name: catalog-server
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./catalog/.env  # Load environment variables from the .env file
    networks:
      - network
    ports:
      - "302:302"

  Customer:
    build: ./customer
    container_name: customer-server
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./customer/.env  # Load environment variables
    networks:
      - network
    ports:
      - "301:301"

  Order:
    build: ./order
    container_name: order-server
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./order/.env  # Load environment variables
    networks:
      - network
    ports:
      - "300:300"

networks:
  network:
    driver: bridge
