name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts  # Avoid the host authenticity check

    - name: Test SSH Connection (GitHub)
      run: ssh -T git@github.com

    - name: Clone repository
      run: git clone git@github.com:resolutedeveloper/ajays-customer-app-api-node-js.git

    - name: Install Dependencies
      run: |
        cd ajays-customer-app-api-node-js
        npm install

    - name: Run Deployment Script
      run: |
        cd ajays-customer-app-api-node-js
        npm run deploy  # Adjust based on your project
