name: Node.js CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/ajaysapi.resolutesolutions.in.net/public_html

          if [ ! -d ".git" ]; then
            echo "Cloning the repository using SSH..."
            git clone git@github.com:resolutedeveloper/ajays-customer-app-api-node-js.git .
          else
            echo "Pulling the latest changes..."
            git pull origin main
          fi

          git status
