name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519  # This will be set in GitHub secrets
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts  # Add GitHub to known hosts to avoid prompt

    - name: Clone repository
      run: git clone git@github.com:resolutedeveloper/ajays-customer-app-api-node-js.git

    - name: Install Dependencies
      run: |
        cd ajays-customer-app-api-node-js
        npm install  # or any other install command for your project

    - name: Run Deployment Script
      run: |
        cd ajays-customer-app-api-node-js
        npm run deploy  # Replace this with your actual deploy command

