name: Service Deploy on Digital Ocean

on:
  workflow_dispatch:  # This allows manual triggering of the workflow
    inputs:
      deploy_service1:
        description: 'Deploy Catalog Service?'
        required: true
        default: 'false'
        type: boolean
      deploy_service2:
        description: 'Deploy Customer Service?'
        required: true
        default: 'false'
        type: boolean
      deploy_service3:
        description: 'Deploy Order Service?'
        required: true
        default: 'false'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/repo/public_html

          if [ ! -d ".git" ]; then
            echo "Cloning the repository using SSH..."
            git clone https://github.com/resolutedeveloper/ajays-customer-app-api-node-js.git .
          else
            echo "Pulling the latest changes..."
            git pull origin main
          fi

    - name: Deploy Catelog using SSH
      if: ${{ github.event.inputs.deploy_service1 == 'true' }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          echo "Deploying Catalog Service..."
          
          # Copy the Catalog files to the target directory
          cp -r /var/www/repo/public_html/Catalog/* /var/www/Catalog/public_html

          echo "move to Catalog service .."
          cd /var/www/Catalog/public_html
          
          echo "installing the lib..."
          npm install

    - name: Deploy Customer using SSH
      if: ${{ github.event.inputs.deploy_service2 == 'true' }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          echo "Deploying Customer Service..."
          
          # Copy the Customer files to the target directory
          cp -r /var/www/repo/public_html/Customer/* /var/www/Customer/public_html

          echo "move to Customer service .."
          cd /var/www/Customer/public_html

          echo "installing the lib..."
          npm install

    - name: Deploy Order using SSH
      if: ${{ github.event.inputs.deploy_service3 == 'true' }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          echo "Deploying Order Service..."
          
          # Copy the Order files to the target directory
          cp -r /var/www/repo/public_html/Order/* /var/www/Order/public_html

          echo "move to Order service .."
          cd /var/www/Order/public_html
          
          echo "installing the lib..."
          npm install

