name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          # Ensure the private key from GitHub secrets is correctly formatted
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/gitaction_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # Add GitHub to known hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Deploy to DigitalOcean
        run: |
          # SSH into the server and perform the deployment
          ssh -o StrictHostKeyChecking=no -A -i ~/.ssh/gitaction_ed25519 root@139.59.1.105 << 'EOF'
            echo "Starting deployment..."

            # Navigate to the app directory
            cd /var/www/ajaysapi.resolutesolutions.in.net/public_html || exit

            # Ensure the directory is clean before cloning
            echo "Removing existing files..."
            rm -rf /var/www/ajaysapi.resolutesolutions.in.net/public_html/*

            # Check if directory is empty before cloning or pull the latest changes
            if [ ! -d ".git" ]; then
              echo "Cloning repository..."
              git clone git@github.com:resolutedeveloper/ajays-customer-app-api-node-js.git .
            else
              echo "Pulling latest changes..."
              git pull origin main
            fi

            # Ensure package.json exists in the root of the repository
            if [ ! -f "package.json" ]; then
              echo "Error: package.json not found in the repository!"
              exit 1
            fi

            echo "Installing dependencies..."
            npm install

            # Check if the ajays.js script exists
            if [ ! -f "ajays.js" ]; then
              echo "Error: ajays.js script not found!"
              exit 1
            fi

            echo "Stopping existing app..."
            pm2 delete ajays || true

            echo "Starting app..."
            pm2 start ajays.js --name ajays

            echo "Deployment complete!"
          EOF
