name: Service Deploy on Digital Ocean

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/repo

          # Check if the repo is already cloned
          if [ ! -d ".git" ]; then
            echo "Cloning the repository using SSH..."
            git clone git@github.com:resolutedeveloper/ajays-customer-app-api-node-js.git .
          else
            echo "Pulling the latest changes..."
            git pull origin main  # Pull the latest changes from the master branch
          fi
