name: Node.js CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  # This will trigger for pull requests targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Ensure the repo is checked out

    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/ajaysapi.resolutesolutions.in.net/public_html
          git pull origin main  # Ensure you're pulling from the main branch
          git status
